### ISSUE TITLE
convert build process to cmake

### ISSUE THREAD

**Issue by pliablepixels** [ozonesecurity/ozonebase#9]
putting up a placeholder - one of us will get to this eventually

**Comment by knight-of-ni** [comment]
Cmake Progress report. 
As stated in #2 , there are a lot of checks in the current build configuration that are not needed. Because of that, I have not finished the CMake work as fast as I would have liked, but progress is being made.

Once I get something that actually works, I'll open a pr for others to test before we merge it.

**Comment by web2wire** [comment]
If it makes any difference I have removed a whole bunch of stuff from configure.ac in the ffmpeg-integration branch which I will try and merge into master shortly (I've managed to merge the other way for now).

**Comment by knight-of-ni** [comment]
Thanks for the tip, I'll check that branch out.

**Comment by web2wire** [comment]
There is probably more to be removed tbh but I'm trying to be cautious.

**Comment by knight-of-ni** [comment]
System checks are done. Now to create the build targets.

**Comment by knight-of-ni** [comment]
I made a lot of progress yesterday. The project builds, but the example programs do not link, complaining avinit can't find one of the ffmpeg functions. Linker problems like this mystify me, since the compiler found the ffmpeg headers just fine. I will have to look into this towards the end of this week when I am back in town.

**Comment by web2wire** [comment]
Finding the header doesn't mean it knows where the libraries are, or what library to find. What version of ffmpeg are you using as later ones have introduced new libraries. I have done some changes in the ffmpeg-integration branch which may be useful but that requires ffmpeg v2.8, which is now a submodule. I have also created a Docker dev image which sets all that up for you and which may be useful to centralise development on so we know everyone is using the same environment. Currently it uses the ffmpeg-itegration branch but you can check out anything once it's set up. I'll merge that branch shortly anyway.

**Comment by knight-of-ni** [comment]
Yes, I understand that finding the header and finding the library to link against are two separate things. The part I apparently have not gotten right is correctly configuring cmake to link the ffmpeg libraries to the build targets properly.

The autotools scripts build just fine. This is not an issue with the version of ffmpeg nor is it anything you have done in the source code. This is purely a cmake issue that I need to work out. I am being scant on details because I am not in front of my development vm at the moment, and I've got one foot out the door. I was merely documenting where I was when I ran out of time yesterday.

**Comment by knight-of-ni** [comment]
I kept telling myself I was doing this right. Turns out the problem was a typo:
https://github.com/knnniggett/ozonebase/blob/cmake/server/CMakeLists.txt#L227

The variable was still set to ZM_BIN_LIBS rather than OZ_BIN_LIBS. Consequently, the avdevice library was not getting linked to the ozone libraries, which caused the example program to fail to link to avdevice.

I think this underscores the need to agree on a process for merging changes to this project. Maybe we can add this as a discussion topic for our next conference. I do plan to be around for our Sunday conference calls eventually. This weekend is a holiday weekend for us Yanks, but I will likely be available. I don't do much on the 4th of July weekend, other than sit at home.

On the ZoneMinder project we generate a pull request and let someone else review it. This let's the rest of the team see what the author intends to do and respond accordingly. This helps minimize the chances of one author's changes negatively affecting another's, which is what happened here when the namespace was changed while I was working on implementing the cmake build. I'd like to agree on a method we can implement to help minimize the chances of mistakes caused by situations like this.
